# Generated by Django 5.0.1 on 2024-01-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_category_menuitem_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=True, upload_to='images/'),
        ),
    ]
